ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS pickup_lat DECIMAL(10,8),
  ADD COLUMN IF NOT EXISTS pickup_lng DECIMAL(11,8),
  ADD COLUMN IF NOT EXISTS pickup_address TEXT,
  ADD COLUMN IF NOT EXISTS dropoff_lat DECIMAL(10,8),
  ADD COLUMN IF NOT EXISTS dropoff_lng DECIMAL(11,8),
  ADD COLUMN IF NOT EXISTS dropoff_address TEXT,
  ADD COLUMN IF NOT EXISTS driver_marked_paid BOOLEAN DEFAULT false;
